name: readme-updater

on:
  pull_request:
  push:
    branches:
      - "master"
      - "readme-updater"

jobs:
  readme-updater:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - uses: actions/setup-node@v2
    
    - run: node readme-generator.js

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate readme
